// //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting 
// with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed nth term, 
// find the sum of the even-valued terms.


function fiboEvenSum(n) {
  // You can do it!
  let count = 0, counter = 0;
  let  i,a=0,b=1;
  while(counter <=n){
    i=a+b;
    a=b;
    b=i;
    if(i %2 ==0)
    {
      count += i; 
    }
    counter++;
  }
  return count;
}
module.exports = fiboEvenSum;
